@baseUrl = http://js-post-api.herokuapp.com/api

# Students

# @name getAllStudents

GET {{baseUrl}}/students?_page=1&_limit=10&name_like

# @name getStudentById
GET {{baseUrl}}/students/

#

# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
      "name": "Berenice Ratke",
      "age": 26,
      "mark": 5.5,
      "gender": "male",
      "createdAt": 1623512826710,
      "updatedAt": 1623512826710,
      "city": "hcm"
}

# @name updateStudent
PATCH {{baseUrl}}/studens/:id
Content-Type: application/json
{
    "name": "Virginie Hoeger"
}

# @name removeStudent
DELETE {{baseUrl}}/students/:id